### ISSUE TITLE
OTRS 5 support

### ISSUE THREAD

**Issue by akosiaris** [znuny/Znuny4OTRS-QuickClose#6]
OTRS 5 has been released a few days ago. http://www.otrs.com/release-notes-otrs-5/

 We are investigating migration of our instance to 5.0.1 and we got this plugin that alas!, needs upgrading. Is there any estimation as to when that might happen ?

**Comment by thorsteneckel** [comment]
Hi @akosiaris! We are currently porting our internal and free addons to OTRS 5. However, this package is on position 4 of the free addons. This means this package should be ported to OTRS 5 in about one month. This is a rough estimation since paid portings for our customers have a higher priority.
I hope that answers your question.

**Comment by akosiaris** [comment]
Hello, @thorsteneckel. Yes it does. Thanks very much for the prompt response

**Comment by dennybresch** [comment]
Hi @akosiaris,
Znuny4OTRS-QuickClose for OTRS 5 is released rel-1.4.0.
Please update Znuny4OTRS-Repo before you update the new version of Znuny4OTRS-QuickClose.

Enjoy!
Your Znuny Team!
